"use client";

import styles from "./auth.module.scss";
import { useState, useEffect, ChangeEvent } from "react";
import Image from "next/image";
import { useNavigate } from "react-router-dom";
import { Path } from "../constant";
import { getClientConfig } from "../config/client";
import { useMsal } from "@azure/msal-react";
import { InteractionStatus } from "@azure/msal-browser";
import { loginRequest, msalConfig } from "../auth/authConfig";
console.log(msalConfig);

export function AuthPage() {
  const navigate = useNavigate();
  const { instance, inProgress } = useMsal();

  const [loginError, setLoginError] = useState<string | null>(null);
  const [isLoggingIn, setIsLoggingIn] = useState(false);
  const [hasAgreed, setHasAgreed] = useState(false);
  const isMsalBusy =
    inProgress === InteractionStatus.Startup ||
    inProgress === InteractionStatus.HandleRedirect;
  const shouldDisableSignIn = !hasAgreed || isLoggingIn || isMsalBusy;

  const serviceLimitations = [
    "Delayed response time due to high volume of requests",
    "Inaccurate or incomplete responses due to the limitations of the AI technology",
    "System crashes or downtime due to technical issues",
    "Message and conversation losses due to whatever reasons",
  ];

  const usageTerms = [
    "The use of the ChatGPT service is voluntary and at the discretion of the user.",
    "The ChatGPT service is available to staff and students of the university only.",
    "The ChatGPT service is provided for informational purposes only and should not be relied upon as a substitute for professional advice or guidance.",
    "The answers provided by the ChatGPT service are generated by artificial intelligence and may contain errors or inaccuracies.",
    "The ChatGPT service is for educational purposes only. Please do not use the service for commercial, illegal or unethical purposes.",
    "The university reserves the right to terminate or suspend the ChatGPT service at any time without prior notice.",
    "The university is not responsible for any information provided by the ChatGPT service.",
    "By using the ChatGPT service, users acknowledge that they have read, understood, and agreed to these terms and conditions.",
  ];
  const logoUrl = process.env.NEXT_PUBLIC_APP_LOGO_URL ?? "";

  const handleAgreementChange = (event: ChangeEvent<HTMLInputElement>) => {
    setHasAgreed(event.target.checked);
  };

  const handleLogin = async () => {
    setLoginError(null);
    setIsLoggingIn(true);
    try {
      const response = await instance.loginPopup(loginRequest);
      if (response?.account) {
        instance.setActiveAccount(response.account);
      }
      navigate(Path.Home);
    } catch (error) {
      const message =
        error instanceof Error
          ? error.message
          : "Unable to login with Microsoft.";
      setLoginError(message);
    } finally {
      setIsLoggingIn(false);
    }
  };

  useEffect(() => {
    if (getClientConfig()?.isApp) {
      navigate(Path.Settings);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div className={styles["auth-page"]}>
      <main className={styles["auth-main"]}>
        <section className={styles["terms-card"]}>
          <Image
            src={logoUrl}
            alt="App Logo"
            width={180}
            height={60}
            className={styles["app-logo"]}
          />
          <div className={styles["terms-content"]}>
            <h1>Terms and conditions for using ChatGPT service</h1>

            <div className={styles["terms-section"]}>
              {loginError && (
                <div className={styles["auth-error"]}>{loginError}</div>
              )}

              <p>
                Please be aware that this is a demo service which may be subject
                to certain instabilities:
              </p>

              <ul>
                {serviceLimitations.map((item) => (
                  <li key={item}>{item}</li>
                ))}
              </ul>

              <p>
                To use the service, staff and students must agree to the
                following terms and conditions:
              </p>

              <ol>
                {usageTerms.map((item, index) => (
                  <li key={`${index}-${item}`}>{item}</li>
                ))}
              </ol>
            </div>

            <div className={styles["checkbox-row"]}>
              <input
                id="agree"
                type="checkbox"
                checked={hasAgreed}
                onChange={handleAgreementChange}
              />
              <label htmlFor="agree">
                I have read, understood, and agreed to the above terms and
                conditions.
              </label>
            </div>
            {!hasAgreed && (
              <div className={styles["agreement-warning"]}>
                Please agree to the terms before signing in.
              </div>
            )}
          </div>

          <button
            type="button"
            className={styles["sign-in"]}
            onClick={handleLogin}
            disabled={shouldDisableSignIn}
          >
            {" "}
            Sign in
          </button>
        </section>
      </main>
    </div>
  );
}
